# Generated by Django 3.2.4 on 2021-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
